name: Code Formatting

on:
  push:
    branches: [main, master, upstream-update]
  pull_request:
    branches: [main, master, upstream-update]

jobs:
  pint:
    runs-on: ubuntu-latest
    name: Laravel Pint
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring
      - uses: ramsey/composer-install@v2
      - name: Run Pint
        run: vendor/bin/pint --test
